version: '2'

services:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: 1234
    depends_on:
      - mysql


